on: [push]

jobs:
  install_fdb:
    name: Install

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install FoundationDB
        uses: ./

      - name: foundationdb status
        run: fdbcli --exec status
